fable-compiler/ts2fable

src/ts2fable.fs, src/typescript.fs
This maps classes as interfaces as specified in #24 and mentioned in #1 & #37. Constructors are also mapped.
electron.fs ends up containing:
``` fs
type [<AllowNullLiteral>] IExports =
abstract BrowserWindow: BrowserWindowStatic with get, set
abstract MenuItem: MenuItemStatic with get, set
abstract Menu: MenuStatic with get, set
abstract NativeImage: NativeImageStatic with get, set
abstract ClientRequest: ClientRequestStatic with get, set
abstract Session: SessionStatic with get, set
abstract Tray: TrayStatic with get, set
type [<AllowNullLiteral>] BrowserWindowStatic =
[<Emit "new $0($1...)">] abstract Create: ?options: BrowserWindowOptions -> BrowserWindow
abstract getAllWindows: unit -> ResizeArray<BrowserWindow>
abstract getFocusedWindow: unit -> BrowserWindow
abstract …
```
=> classes mapped as interfaces

src/ts2fable.fs, test-compile/test-compile.fsproj
This allows multiple TypeScript files to be specified as input. I'm still not sure what to do with F# namespaces and JavaScript imports #21. I think it is a good idea to merge this is and have people try it out and give feedback. Some namespaces and imports will have to be manually corrected.
=> allow multiple ts file as input

src/read.fs
fix fable-compiler/ts2fable#92
=> get underlying type from ParenthesizedType

src/transform.fs
from yargs, this fixed this case:
``` ts
declare var yargs: yargs.Argv;
export = yargs;
```
=> check if export is a variable

src/transform.fs, test-compile/test-compile.fsproj
see #103
This makes it:
``` fs
module resolve =
type [<AllowNullLiteral>] IExports =
abstract __promisify__: hostname: string * ?rrtype: U5<string, string, string, string, string> -> Promise<ResizeArray<string>>
[<Emit "$0.__promisify__($1,'MX')">] abstract __promisify___MX: unit -> Promise<ResizeArray<MxRecord>>
[<Emit "$0.__promisify__($1,'NAPTR')">] abstract __promisify___NAPTR: unit -> Promise<ResizeArray<NaptrRecord>>
[<Emit "$0.__promisify__($1,'SOA')">] abstract __promisify___SOA: unit -> Promise<SoaRecord>
[<Emit "$0.__promisify__($1,'SRV')">] abstract __promisify___SRV: unit -> Promise<ResizeArray<SrvRecord>>
[<Emit "$0.__promisify__($1,'TXT')">] abstract __promisify___TXT: unit -> Promise<ResizeArray<ResizeArray<string>>>
abstract __promisify__: hostname: string * ?rrtype: …
```
=> allow string literal overloads on any param

src/Node.fs, src/TypeScript.fs, src/read.fs
TypeScript 2.2 introduced the `object` type. I lot of TypeScript definitions would be better to use that rather than `any`. Any, unfortunately, can be `null` or `undefined`. Definitions that use a lot of `any` types could make the APIs a bit harder to use.
https://blog.mariusschulz.com/2017/02/24/typescript-2-2-the-object-type
I'm going to merge this in, but if it makes the generated APIs suck too much, let me know and perhaps we can add a command line option to relax it to just `obj` instead of `obj option`.
=> any may be null or undefined

src/Node.fs, src/TypeScript.fs, src/Yargs.fs, src/naming.fs, src/read.fs, src/syntax.fs, src/transform.fs, src/ts2fable.fs, src/version.fs, src/write.fs, test-compile/test-compile.fsproj, test/test.fs
The sub-modules need to be exported too. I ran into the problem where module names and these let bindings can't be the same. Currently thinking about UpperCamelCase for module names and camelCase for the lets. Open to review.
``` fs
module Fs =
let [<Import("constants","fs")>] constants: constants.IExports = jsNative
```
It then can be used like:
``` fs
printfn "Node O_RDWR %A" Node.Fs.constants.O_RDWR 
```
=> export sub modules too

package.json, src/ts2fable.fs, test-compile/test-compile.fsproj
to fix  #132
If this fixes it, I'd like to put it back in, but need to figure out how to remove this from package.json
``` js
"engines": {
"vscode": "1.18.1"
}
```
=> temporarily remove vscode tests

src/read.fs, src/transform.fs, src/write.fs, test/fragments/react/f1.d.ts, test/fragments/react/f1.fs, test/fsFileTests.fs, tools/webpack.config.test.js
```typescript
declare namespace React {
type Ref<T> = string | { bivarianceHack(instance: T | null): any }["bivarianceHack"];
}
```
```fsharp
type Ref<'T> =
U2<string, ('T option -> obj option)>
```
`This construct is deprecated: This type abbreviation has one or more declared type parameters that do not appear in the type being abbreviated. Type abbreviations must use all declared type parameters in the type being abbreviated. Consider removing one or more type parameters, or use a concrete type definition that wraps an underlying type, such as 'type C<'a> = C of ...'.`
```fsharp
type Ref<'T> =
U2<string, obj>
```
=> Read IndexedAccessType && Extract type literal from union

README.md, dotnet-fake.proj, fake.cmd, fake.sh
@humhei I bootstrapped fake inside the repo otherwise, people need to install it globally and on unix system we don't have the chocolatey equivalent.
I used OS X to build the repo, so I updated the README.md file. In order, to build the repo I needed to run the `Deploy` target so it's install all the dependencies (nuget, npm), restore projects etc.
But from a user perspective it's feel really strange to run `Deploy`. I needed to read the `build.fsx` to make sure was not going to push a version to the server.
I think se should have something like:
```fs
Target.Create "CliTest" Target.DoNothing
Target.Create "Deploy" DoNothing
Target.Create "Setup" Target.DoNothing
"InstallDotNetCore"
==> "YarnInstall"
==> "Restore"
==> "Setup"
"CliTest"
<== [ "Setup"
"BuildCli"
"RunCli"
"BuildTestCompile" …
```
=> Add bootstrap fake + update docs

src/bridge.fs, src/transform.fs
sweet, this seems to work:
closes https://github.com/fable-compiler/ts2fable/issues/272
ToDo: some unit tests probably. Haven't looked at the test structure
=> unwrap options if the parameter itself is optional

src/bridge.fs, src/read.fs, src/syntax.fs, src/transform.fs
The reason for this PR is that babylonJs has many private members in their .d.ts:
```
Find all "private", Match case, Whole word, Find Results 1, Current Document
Matching lines: 2592
```
I wasn't able to test it at all, because the build fails for me locally
=> remove private members from classes

src/bridge.fs, src/transform.fs
references https://github.com/fable-compiler/ts2fable/issues/279
This removes the compiler error, but keeps double and float
=> fix "type float = float" (babylonjs)

src/transform.fs, test/fragments/babylonjs/.gitignore, test/fragments/babylonjs/SceneLoader.ImportMeshAsync.d.ts, test/fragments/babylonjs/SceneLoader.ImportMeshAsync.expected.fs, test/fragments/babylonjs/Stage.PrivateCtor.d.ts, test/fragments/babylonjs/Stage.PrivateCtor.expected.fs, test/fragments/regressions/#275-private-members.d.ts, test/fragments/regressions/#275-private-members.expected.fs, test/fragments/regressions/#277-unwrap-options.d.ts, test/fragments/regressions/#277-unwrap-options.expected.fs, test/fragments/regressions/#278-typeliterals-return.d.ts, test/fragments/regressions/#278-typeliterals-return.expected.fs, test/fragments/regressions/#288-type-alias-float-number.d.ts, test/fragments/regressions/#288-type-alias-float-number.expected.fs, test/fragments/regressions/#289-recursive-merge-modules.d.ts, test/fragments/regressions/#289-recursive-merge-modules.expected.fs, test/fragments/regressions/.gitignore, test/fsFileTests.fs, test/test.fsproj
extract all type literals which hadn't already been extracted by the first pass.
These won't have the same nice names as in the first pass, because the extractor doesn't have enough context (class name, method name, etc), but will instead be named like "TypeLiteral_%02i"
-----------------------
This is a WIP so I can review the ts2fable-exports.
I am currently writing tests 🙃 
-------------------------
fixes https://github.com/fable-compiler/ts2fable/issues/286
=> add a second pass to 'extractTypeLiterals'

src/transform.fs, test/fragments/babylonjs/SceneLoader.ImportMeshAsync.expected.fs, test/fragments/babylonjs/Stage.PrivateCtor.expected.fs
bABYLON looked really odd. This changes module names that are all uppercase to all lowercase instead of just lowercasing the first letter.
=> Don't convert 'BABYLON' to 'bABYLON'

README.md
interacting.md is dead and returns 404 Not Found.
=> Replace interacting.md with the new documentation

web-app/webpack.config.js
`.\fake.cmd run .\build.fsx -t WebApp.Watch` launches a web server serving web-app under `localhost:8080`.  
But: loading that site doesn't work. It just loads forever displaying "We are getting everything ready for you".
JS Console shows: it can't load `require.js`.
Reason: the web-app server serves content from the wrong folder (`public` vs `output`)
=> Fix: web-app stuck at loading

src/naming.fs, test/fragments/babylonjs/SceneLoader.ImportMeshAsync.expected.fs, test/fragments/babylonjs/Stage.PrivateCtor.expected.fs, test/fragments/breezejs/globalVariable.fs, test/fragments/monaco/variableInModule.fs, test/fragments/react/f5.fs, test/fragments/reactxp/duplicatedVariableExports.fs, test/fragments/reactxp/multiple/ReactXP.fs, test/fragments/regressions/#275-private-members.expected.fs, test/fragments/regressions/#277-unwrap-options.expected.fs, test/fragments/regressions/#278-typeliterals-return.expected.fs, test/fragments/regressions/#288-type-alias-float-number.expected.fs, test/fragments/regressions/#289-recursive-merge-modules.expected.fs, test/fragments/regressions/#292-static-props.expected.fs, test/fsFileTests.fs, test/functionTests.fs
fixes #229
Currently `ts2fable` requires an input path with `node_modules`.   
Especially using `index.d.ts` in cwd doesn't work (`ts2fable index.d.ts out.fs`) and results in `Error: List was empty` (see #229).  
Other paths without `node_modules` produce unexpected module names (in `[<Import("[...]","XXX")>]`). For example: `ts2fable "E:\prog\fsharp\vscode.d.ts" out.fs` -> `[<Import("*","E:")>]`. Instead of file name (or last dir name in case of index.d.ts) ts2fable takes the first part as module name. Similar with `ts2fable ../index.d.ts out.fs` -> `[<Import("*","..")>]`
Currently ts2fable extracts the module name from the passed .d.ts path. This PR resolves the path to an absolute one. This should make module name generation more robust and handle relative paths and paths without …
=> Fix: ts2fable requires input path with `node_modules`

src/bridge.fs, src/print.fs, src/read.fs, src/syntax.fs, src/transform.fs, test-compile/test-compile.fsproj, test/fragments/custom/generic-type-constraints/and.d.ts, test/fragments/custom/generic-type-constraints/and.expected.fs, test/fragments/custom/generic-type-constraints/combination.d.ts, test/fragments/custom/generic-type-constraints/combination.expected.fs, test/fragments/custom/generic-type-constraints/default.d.ts, test/fragments/custom/generic-type-constraints/default.expected.fs, test/fragments/custom/generic-type-constraints/etc.d.ts, test/fragments/custom/generic-type-constraints/etc.expected.fs, test/fragments/custom/generic-type-constraints/function.d.ts, test/fragments/custom/generic-type-constraints/function.expected.fs, test/fragments/custom/generic-type-constraints/invalid_fsharp.d.ts, test/fragments/custom/generic-type-constraints/or.d.ts, test/fragments/custom/generic-type-constraints/or.expected.fs, test/fragments/custom/generic-type-constraints/sealed.d.ts, test/fragments/custom/generic-type-constraints/sealed.expected.fs, test/fragments/custom/generic-type-constraints/simple.d.ts, test/fragments/custom/generic-type-constraints/simple.expected.fs, test/fragments/custom/generic-type-constraints/types.d.ts, test/fragments/custom/generic-type-constraints/types.expected.fs, test/fragments/react/f2.fs, test/fragments/react/f4.fs, test/fragments/react/f6.fs, test/fragments/react/f7.fs, test/fsFileTests.fs
Fixes #84
Adds handling of generic type parameter constraints.
Beside simple constraints (like `T extends A` -> `'T when 'T :> A`), intersections are handled: `T extends A & B` -> `'T when 'T :> A and 'T :> B`. Unions aren't supported (`'T extends A | B`)
Special behaviour:
* Unsupported constraints are ignored: `type MyType<'T extends A | B> = ...` -> `type MyType<'T> = ...`
* Types that are sealed in F# are ignored (like `Function` -> `System.Action`)
* Unsupported parts in intersections are ignored, while all others are handled: `'T extends A & Function & B & (C | D)` -> `'T when 'T :> A and 'T :> B`
<br/>
<br/>
Constraints in Typescript are quite versatile. Quite often they cannot be translated directly into F# (without a lot of effort...). And unfortunately not all such cases can be …
=> Add generic type parameter constraints

test/fragments/regressions/#368-compare-xml-comments.fail.d.ts, test/fragments/regressions/#368-compare-xml-comments.fail.expected.fs, test/fragments/regressions/#368-compare-xml-comments.pass.d.ts, test/fragments/regressions/#368-compare-xml-comments.pass.expected.fs, test/fsFileTests.fs
Inspired by https://github.com/fable-compiler/ts2fable/pull/367#pullrequestreview-530824836
Currently xml comments (`///`) are ignored during testing -> Files with same code, but different xml comments still match.  
This changes that: XML comments must match too. Normal comments (`//`) are still ignored.
=> Add comparison of xml comments for tests

src/transform.fs, test/fragments/regressions/#374-string-literal-type-argument-with-space.d.ts, test/fragments/regressions/#374-string-literal-type-argument-with-space.expected.fs, test/fsFileTests.fs
Fix #374: Invalid function name when parameter with string literal type contains space
Note: Currently some invalid characters are recognized as valid in identifier, like `☕`.  
`Char.IsLetterOrDigit` returns wrong result. It's fixed in Fable 3, and will be fixed in ts2fable with #373. Once merged some additional tests might be commented in (-> `test\fragments\regressions\#374-string-literal-type-argument-with-space.*`)
=> Fix #374: Invalid function name when parameter with string literal type contains space

src/ts2fable.fs
Previously: exit code was always `0`
Now: returns `1` if error
=> Return non-0 exit code when error

src/naming.fs, test/functionTests.fs
> Error: toText(...)(...) is not a function
-> Exception in `ts2fable.Name.capitalize` when input starts with `%`
Usually something like
```typescript
export type Operator =
"==" | ... | "%" | ... | "%=" | ...;
```
(happens in packages `estree` & `babel-types`)
Error in Fable: https://github.com/fable-compiler/Fable/issues/2398
Fix until resolved: use string addition instead of formatter
Add some `capitalize` tests including `%` tests
=> Fix: Exception when string identifier `%`

src/naming.fs, test/fragments/regressions/#374-string-literal-type-argument-with-space.d.ts, test/fragments/regressions/#374-string-literal-type-argument-with-space.expected.fs
happend for something like:
```typescript
on(event: "post-require"): void;
```
(from: mocha)
Was escaped once in transform because string literal identifier with invalid token
and 2nd time in `escapeWord` because of hyphen
Note: `escapeWord` and co might need a redo:
* different allowed chars for module/type vs. function/variable name (type doesn't allow something like `$`)
* not all invalid characters are currently handled
* (further complication: `.` not allowed in type -- but in type name in `escapeWord` because might be namespace/module.type)
=> Fix: surrounded by 4 backticks when string lit. & hyphen

package-lock.json, package.json, web-app/webpack.config.js
SourceMaps need `source-map-loader` to work with webpack.
See: https://github.com/MangelMaxime/fulma-demo/pull/43#issuecomment-756556346
=> Fix: Source Maps (in Web App) don't work

src/bridge.fs, src/naming.fs, test/fragments/custom/generic-type-constraints/and.expected.fs, test/fragments/custom/generic-type-constraints/default.expected.fs, test/fragments/custom/generic-type-constraints/function.expected.fs, test/fragments/custom/generic-type-constraints/or.expected.fs, test/fragments/custom/generic-type-constraints/sealed.expected.fs, test/fragments/regressions/#275-private-members.expected.fs, test/fragments/regressions/#277-unwrap-options.expected.fs, test/fragments/regressions/#278-typeliterals-return.expected.fs, test/fragments/regressions/#288-type-alias-float-number.expected.fs, test/fragments/regressions/#289-recursive-merge-modules.expected.fs, test/fragments/regressions/#292-static-props.expected.fs, test/fragments/regressions/#303-EmitConstructor.expected.fs, test/fragments/regressions/#303-EmitIndexer.expected.fs, test/fragments/regressions/#314-inline-destruct.expected.fs, test/fragments/regressions/#352-generic-type-parameter-default.expected.fs, test/fragments/regressions/#353-generic-type-parameter-default-type.expected.fs, test/fragments/regressions/#362-paramarray.expected.fs, test/fragments/regressions/#368-compare-xml-comments.fail.expected.fs, test/fragments/regressions/#368-compare-xml-comments.indented.fail.expected.fs, test/fragments/regressions/#368-compare-xml-comments.pass.expected.fs, test/fragments/regressions/#374-string-literal-type-argument-with-space.expected.fs, test/fragments/regressions/#382-package-with-hyphen-in-name-produces-invalid-module-name-with-hyphen.d.ts, test/fragments/regressions/#382-package-with-hyphen-in-name-produces-invalid-module-name-with-hyphen.expected.fs, test/fsFileTests.fs
Fix #382: packe name with `-` -> invalid root module name
Root module name (= package name) is now treated the same way as other
identifiers
-> if hyphen or keyword the name gets surrounded with double-backticks
Note: all regression tests (`*.expected.fs` files) had to be changed:
they contain `-` in title -> has to be escaped with backticks. Their
test contents remained untouched.
Same for several other tests (F# keyword as name like `default`).
=> Fix #382: packe name with `-` results in invalid root module name

src/transform.fs, test/fragments/regressions/#386-TS-types.d.ts, test/fragments/regressions/#386-TS-types.expected.fs, test/fsFileTests.fs
Partial fix of #386: Handle ArrayLike & PromiseLike
`ArrayLike` -> `System.Collections.Generic.IList<'T>`
`PromiseLike` -> `Fable.Core.JS.Promise<'T>`
=> Partial fix of #386: Handle ArrayLike & PromiseLike

.config/dotnet-tools.json, src/transformComments.fs
Fable was updated to handle named capture groups for regexes
-> use .NET group accessor instead of JS dynamic typing hack
=> Remove hack to use regex with named groups

src/read.fs, test/fragments/monaco/variableInModule.fs, test/fragments/reactxp/duplicatedVariableExports.fs, test/fragments/reactxp/multiple/ReactXP.fs, test/fragments/regressions/#393-mutable-variables-become-immutable.d.ts, test/fragments/regressions/#393-mutable-variables-become-immutable.expected.fs, test/fragments/regressions/#394-comments-on-variables-in-modules.expected.fs, test/fsFileTests.fs
Works with variables in modules & namespaces.
Doesn't work with top-level variables:
```typescript
export let v: number;
```
`v` is mutable and should be converted into:
```fsharp
let [<Import(...)>] mutable v: float = jsNative
```
BUT: ts2fable places everything in a recursive module:
```fsharp
module rec Name
open System
//...
let [<Import(...)>] mutable v: float = jsNative
```
In a rec module, mutable let bindings aren't allowed:
> error FS0874: Mutable 'let' bindings can't be recursive or defined in
recursive modules or namespaces
-> would require change of generated code for top-level variables.
Instead these variables are still immutable.
=> Fix #393: Mutable variables become immutable

src/print.fs, src/syntax.fs, src/transformComments.fs, test/fragments/custom/comments/transformToXml.expected.fs, test/fragments/regressions/#403-xml-comment-escape-chars.d.ts, test/fragments/regressions/#403-xml-comment-escape-chars.expected.fs, test/fsFileTests.fs
Note: only `&` and `<` get escaped, NOT `>'"`. These are not necessary
for F# compiler.
But results in some strange constructs like `&lt;exception>` -> Start is
escaped, But end isn't.
=> Fix #403: Unescaped Chars in XML Comments

src/syntax.fs, src/transformComments.fs, test/fragments/custom/comments/transformToXml.expected.fs, test/fragments/regressions/#393-mutable-variables-become-immutable.expected.fs, test/fragments/regressions/#403-xml-comment-escape-chars.d.ts, test/fragments/regressions/#403-xml-comment-escape-chars.expected.fs
Previous fix escaped chars before converting markdown/jsdoc into xml.
That included a test for xml tag (-> simple summary doesn't need a
`<summary>` tag -> doesn't need escaping).
In Combination with an incorrect test, that resulted in `<` and `&` not
beeing escaped most of the time.
Additional: `>` gets escaped too. `&lt;tag>` just looks to strange. But
disadvantage: Start of Markdown Quote (`> ...`) or arrow (`->`) look
strange in xml doc comment code (`-&gt;`, `&gt; some quote`).
=> Fix #403: Unescaped Chars in XML Comments (2nd try)

src/print.fs, src/transform.fs, test/fragments/regressions/#401-variable-generic.d.ts, test/fragments/regressions/#401-variable-generic.expected.fs, test/fsFileTests.fs
Handles only Namespaces/Modules & Interfaces/Classes (-> interface), NOT top-level variables (-> `let` binding).
=> Partial Fix of #401: Variables & Properties with generic type parameter

package-lock.json, src/config.fs, src/print.fs, src/ts2fable.fs, src/ts2fable.fsproj, test/fragments/regressions/#428-noresizearray.d.ts, test/fragments/regressions/#428-noresizearray.expected.fs, test/fragments/regressions/#429-convertpropfns.d.ts, test/fragments/regressions/#429-convertpropfns.expected.fs, test/fsFileTests.fs, web-app/App.fs, web-app/sass/main.scss
This PR provides options for using `'T[]` instead of `ResizeArray<'T>`, and for generating member functions instead of lambda property getters. See issues #428 #429 for details.
The options are accessible from:
- command line
- web app
- test suite
```bash
Usage: ts2fable some.d.ts src/Some.fs
Options:
--export             Collect from multiple TS files
--noresizearray      Use 'T[] instead of ResizeArray<'T>
--convertpropfns     Convert lambda properties to member functions
--version            Show tool version
--help               Show command usage
```
Include command line flags in the source `.d.ts`. For example
File: `tests/fragments/regressions/#429-convertpropfns.d.ts`
```typescript
//--convertpropfns
declare class Appwrite {
account: {
createDocument: (name: string) => Document; …
```
=> --noresizearray, --convertpropfns (issues #428, 429)

package-lock.json, src/print.fs, test/fragments/babylonjs/SceneLoader.ImportMeshAsync.expected.fs, test/fragments/babylonjs/Stage.PrivateCtor.expected.fs, test/fragments/monaco/variableInModule.fs, test/fragments/react/f5.fs, test/fragments/reactxp/duplicatedVariableExports.fs, test/fragments/reactxp/multiple/ReactXP.fs, test/fragments/regressions/#431-import-all.d.ts, test/fragments/regressions/#431-import-all.expected.fs, test/fsFileTests.fs
Output
```fsharp
let [<ImportAll("my-module")>] myModule: MyModule.IExports = jsNative
```
instead of
```fsharp
let [<Import("*", "my-module")>] myModule: MyModule.IExports = jsNative
```
Generate same import (with `*`), see [Fable Docs](https://fable.io/docs/communicate/js-from-fable.html#type-safety-with-imports-and-interfaces)
=> Emit `ImportAll(..)` instead of `Import("*",...)`

src/print.fs, src/read.fs, src/transform.fs, src/transformComments.fs, test/fragments/babylonjs/SceneLoader.ImportMeshAsync.expected.fs, test/fragments/babylonjs/Stage.PrivateCtor.expected.fs, test/fragments/custom/comments/transformToXml.expected.fs, test/fragments/custom/type-literal-indexer.d.ts, test/fragments/custom/type-literal-indexer.expected.fs, test/fragments/custom/type-literal.d.ts, test/fragments/custom/type-literal.expected.fs, test/fragments/monaco/variableInModule.fs, test/fragments/react/f7.fs, test/fragments/regressions/#278-typeliterals-return.d.ts, test/fragments/regressions/#278-typeliterals-return.expected.fs, test/fragments/regressions/#314-inline-destruct.expected.fs, test/fragments/regressions/#400-type-literal-in-union-type.d.ts, test/fragments/regressions/#400-type-literal-in-union-type.expected.fs, test/fragments/regressions/#428-noresizearray.expected.fs, test/fsFileTests.fs
Convert Anonymous JS Object Types into F# Anonymous Records (as discussed in comments of #400).  
That's only done when object has `<= 4` members. Otherwise it's still extracted into an Interface:
```typescript
export const c1: { v1: string }
export const c5: { v1: string, v2: number, v3: number, v4: string, v5: string }
```
==>
```fsharp
let [<Import(...)>] c1: {| v1: string |} = jsNative
let [<Import(...)>] c5: C5 = jsNative
type [<AllowNullLiteral>] C5 =
abstract v1: string with get, set
// ...
```
`3` or `4` seems like a reasonable split. I decided for `4`.
There's an important difference between Anon Record & Interface: Properties in Anon Record are always immutable, while in Interface they are mutable unless the field is marked as readonly (`{ readonly value: string }`).
Currently …
=> Convert Anonymous Object Type into Anonymous Records & Fix #400

src/print.fs, test/fragments/custom/comments/obsolete.expected.fs, test/fragments/custom/comments/types.expected.fs, test/fragments/custom/type-literal.expected.fs, test/fragments/monaco/variableInModule.fs, test/fragments/react-native-fbsdk/stringEnumWithPeriod.fs, test/fragments/react/f2.fs, test/fragments/react/f7.fs, test/fragments/regressions/#374-string-literal-type-argument-with-space.expected.fs, test/fragments/regressions/#438-tagged-union.expected.fs
Fable doc uses parens -> use parens here too
Previously: mixed: sometimes parens, sometimes space
=> Always surround args in Attributes in parens

src/print.fs, test/fragments/regressions/#450-obsolete-multiline.d.ts, test/fragments/regressions/#450-obsolete-multiline.expected.fs, test/fsFileTests.fs
```typescript
declare namespace ns1 {
namespace ns2 {
interface SomeInterface {
/**
* @deprecated 
* Value is deprecated
* etc.
*/
Value: number
}
}
}
```
->
```fsharp
module Ns1 =
module Ns2 =
type SomeInterface =
[<Obsolete("Value is deprecated
etc.")>]
abstract Value: float with get, set
```
-> Obsolete ends with wrong indentation, must be (at least):
```fsharp
module Ns1 =
module Ns2 =
type SomeInterface =
[<Obsolete("Value is deprecated
etc."       )>]
abstract Value: float with get, set
```
<br/>
<br/>
This PR ensures attributes end at correct indentation and adds spaces at the the end of arguments if necessary.
=> Fix: Deprecated/Obsolete with Reason spanning multiple lines might result in invalid F# (wrong indentation/alignment)

src/bridge.fs, src/print.fs, src/syntax.fs, src/transform.fs, test/fragments/regressions/#454-extends-enum.d.ts, test/fragments/regressions/#454-extends-enum.expected.fs, test/fsFileTests.fs
```typescript
enum RootKind {
Alpha = 1,
Beta = 2,
}
interface InterfaceRootKind<TKind extends RootKind> { }
```
prev:
```fsharp
type [<AllowNullLiteral>] InterfaceRootKind<'TKind when 'TKind :> RootKind> = interface end
```
-> `:> RootKind` is invalid
now:
```fsharp
type [<AllowNullLiteral>] InterfaceRootKind<'TKind when 'TKind : enum<int>> = interface end
```
Note:  
There's no additional XML Comment because that would need handling of outer type instead of just Generic Type Parameter (... and I got lazy... :P )
If we add comments in such cases we should do that for all cases Constraints gets adjusted or removed, not just for enum
<br/>
<br/>
-----------
<br/>
<br/>
Additional:  
Increase timeout for tests (`15s` -> `25s`)
previous master CI test failed (with timeout of a test) -- while …
=> Handle extends int enum

src/naming.fs, src/print.fs, src/syntax.fs, test/fragments/regressions/#423-invalid-du-case-name.d.ts, test/fragments/regressions/#423-invalid-du-case-name.expected.fs, test/fsFileTests.fs
```typescript
export type CompletionsTriggerCharacter = 
| "@"
| "."
| "+"
| "$"
| "&"
| "["
| "]"
| "/"
| "\\"
| "*"
| "\""
| "`"
| "'" 
| "<" 
| "#" 
| " " 
| "-"
| "_"
| "\t"
| "\n"
| "\r\n"
| "////" 
| "\\\\\\" 
| "@\t\\\n"
| "<@\t\\\n>"
| "A\"B\\C&D+E@F"
; 
```
->
```fsharp
type [<StringEnum>] [<RequireQualifiedAccess>] CompletionsTriggerCharacter =
| [<CompiledName("@")>] AT
| [<CompiledName(".")>] DOT
| [<CompiledName("+")>] PLUS
| [<CompiledName("$")>] DOLLAR
| [<CompiledName("&")>] AMPERSAND
| [<CompiledName("[")>] LEFT_SQUARE_BRACKET
| [<CompiledName("]")>] RIGHT_SQUARE_BRACKET
| [<CompiledName("/")>] SLASH
| [<CompiledName("\\")>] BACKSLASH
| [<CompiledName("*")>] ASTERISK
| [<CompiledName("\"")>] QUOTATION
| [<CompiledName("`")>] BACKTICK
| [<CompiledName("'")>] ``'``
| …
```
=> Fix #423: Invalid DU Case names (special chars)

src/read.fs, test/fragments/regressions/#456-generic-call-signature.d.ts, test/fragments/regressions/#456-generic-call-signature.expected.fs, test/fsFileTests.fs
```typescript
export interface Node {}
export interface NodeVisitor {
<T extends Node>(nodes: T)
<T extends Node>(nodes: T, test: (node: T) => boolean)
}
```
prev:
```fsharp
type [<AllowNullLiteral>] Node =
interface end
type [<AllowNullLiteral>] NodeVisitor =
[<Emit("$0($1...)")>] abstract Invoke: nodes: T -> unit
[<Emit("$0($1...)")>] abstract Invoke: nodes: T * test: (T -> bool) -> unit
```
-> doesn't handle generic & its constraint
now:
```fsharp
type [<AllowNullLiteral>] Node =
interface end
type [<AllowNullLiteral>] NodeVisitor =
[<Emit("$0($1...)")>] abstract Invoke: nodes: 'T -> unit when 'T :> Node
[<Emit("$0($1...)")>] abstract Invoke: nodes: 'T * test: ('T -> bool) -> unit when 'T :> Node
```
=> Handle generic call signature

src/transform.fs, test/fragments/regressions/#457-overload-anon-record.d.ts, test/fragments/regressions/#457-overload-anon-record.expected.fs, test/fsFileTests.fs
```typescript
export const createStringLiteral: {
(text: string, isSingleQuote?: boolean | undefined): StringLiteral;
(text: string, isSingleQuote?: boolean | undefined, hasExtendedUnicodeEscape?: boolean | undefined): StringLiteral;
};
```
prev:
```fsharp
let [<Import("createStringLiteral","module")>] createStringLiteral: {| Invoke: string -> bool option -> StringLiteral; Invoke: string -> bool option -> bool option -> StringLiteral |} = jsNative
```
-> Two `Invoke` Properties  
-> invalid
now: interface instead of anon record when functions/properties with same name
```fsharp
type [<AllowNullLiteral>] CreateStringLiteral =
[<Emit("$0($1...)")>] abstract Invoke: text: string * ?isSingleQuote: bool -> StringLiteral
[<Emit("$0($1...)")>] abstract Invoke: text: string * ?isSingleQuote: bool …
```
=> Fix: Type Literal with overload generates Anonymous Record with two Properties of same name

build.fsx, test/fsFileTests.fs
In the last PR I forgot to remove `Only` from a test -> just that one test runs  
-> fixed in this PR
To prevent this in the future, with this PR `RunTest` fails when there are focused (`itOnly`) tests. Watching tests (`WatchAndRunTest`) still allows `itOnly`.  
-> `itOnly` still ok during development (-> watch test), but fails in full build and especially on CI
=> Fail on focused (`itOnly`) test

src/bridge.fs, src/read.fs, src/syntax.fs, src/transform.fs, src/ts2fable.fsproj, src/utils.fs, test/fragments/regressions/#451-union-enum-sub-sets.expected.fs, test/fragments/regressions/#460-union-of-all-same-type.d.ts, test/fragments/regressions/#460-union-of-all-same-type.expected.fs, test/fsFileTests.fs
Follow up(ish) to #451
```typescript
enum Kind {
Alpha = 1,
Beta = 2,
Gamma = 3,
Delta = 4,
}
interface Token<TKind extends Kind> {}
type TokenBC1 = Token<Kind.Beta | Kind.Gamma>
type TokenBC2 = Token<Kind.Beta> | Token<Kind.Gamma>
type TokenBeta = Token<Kind.Beta>
type TokenGamma = Token<Kind.Gamma>
type TokenBC3 = TokenBeta | TokenGamma
```
Currently:
```fsharp
//[...]
type TokenBC1 =
Token<Kind>
type TokenBC2 =
Token<Kind>
type TokenBeta =
Token<Kind>
type TokenGamma =
Token<Kind>
type TokenBC3 =
U2<TokenBeta, TokenGamma>
```
-> Unlike `TokenBC1` & `2`, `TokenBC3` doesn't get reduced to `Token<Kind>`, because it doesn't directly use `Token<...>`, but instead via Alias.
With this PR `TokenBC3` gets reduced to `Token<Kind>` too:
```fsharp
type TokenBC3 =
Token<Kind>
```
<br/> …
=> Unify indirect Enum-Case-Usage with all source Enum

src/print.fs, test/fragments/regressions/#454-extends-enum.expected.fs, test/fragments/regressions/#460-union-of-all-same-type.expected.fs
There's a bug in FCS that produces compiler error when `enum` constraint, `rec` module, and type alias or inheritance  
see https://github.com/dotnet/fsharp/issues/14580
Solution for now is to not use `enum` constraint
Should be enabled again once bug is fixed
=> Disable `enum` constraint

src/bridge.fs, src/syntax.fs, src/transform.fs, test/fragments/regressions/#463-literal-parameters.d.ts, test/fragments/regressions/#463-literal-parameters.expected.fs, test/fsFileTests.fs
Currently only string literals are handled, but not bool, int, float literals:
```typescript
function myTest3(v: "hello")
function myTest8(v: 3.14)
function myTest9(v: 42)
function myTest10(v: true)
```
->
```fsharp
[<Emit("$0.myTest3('hello')")>] abstract myTest3_hello: unit -> unit
abstract myTest8: v: float -> unit
abstract myTest9: v: int -> unit
abstract myTest9: v: bool -> unit
```
With this PR float, int, and bool literals are now emitted too:
```fsharp
[<Emit("$0.myTest3('hello')")>] abstract myTest3_hello: unit -> unit
[<Emit("$0.myTest8(3.14)")>] abstract ``myTest8_3.14``: unit -> unit
[<Emit("$0.myTest9(42)")>] abstract myTest9_42: unit -> unit
[<Emit("$0.myTest10(true)")>] abstract myTest10_true: unit -> unit
```
=> Handle bool,int,float Literal parameters

src/bridge.fs, test/fragments/regressions/#464-duplicated-method-in-generated-interface.d.ts, test/fragments/regressions/#464-duplicated-method-in-generated-interface.expected.fs, test/fsFileTests.fs
```typescript
const node: {
(arg: string): boolean
(arg: string): boolean
}
```
currently produces:
```fsharp
type [<AllowNullLiteral>] IExportsNode =
[<Emit("$0($1...)")>] abstract Invoke: arg: string -> bool
[<Emit("$0($1...)")>] abstract Invoke: arg: string -> bool
```
-> error:
> Duplicate method. The method 'Invoke' has the same name and signature as another method in type '[...].IExportsNode'.
In other cases duplicated methods already get reduced -- but here that didn't happen
=> Fix: Duplicated Method in generated Interface when TS has duplicated method

src/bridge.fs, src/config.fs, src/transform.fs, src/ts2fable.fs, test/fragments/custom/obsolete/dont-remove-obsolete.d.ts, test/fragments/custom/obsolete/dont-remove-obsolete.expected.fs, test/fragments/custom/obsolete/remove-obsolete.d.ts, test/fragments/custom/obsolete/remove-obsolete.expected.fs, test/fsFileTests.fs, web-app/App.fs
Elements annotated with `@deprecated` get marked with `[<Obsolete(...)>]` in F#.  
But sometimes it's easier to handle a smaller F# file while ignoring all deprecated/obsolete elements.
This PR adds `--remove-obsolete` option to remove `Obsolete` elements.
Unfortunately that's not that trivial: Elements might reference `@deprecated` elements -> requires usage analysis.  
I currently don't do this, but instead remove only `Obsolete` elements that cannot be referenced: Functions, Properties and Variables. But not other elements like Interfaces, Aliases, Modules (-> still in output F# code and marked with `Obsolete`)
<br/>
<br/>
------------------
<br/>
<br/>
Note: (just in case somebody stumbles across it -- happens in new test files)  
`Obsolete` (with `System` open) (or any Attribute) on …
=> Add Option to remove `Obsolete` Functions, Properties, Variables

src/transform.fs, test/fragments/regressions/#466-generic-type-param-default-refs-other-type-param.d.ts, test/fragments/regressions/#466-generic-type-param-default-refs-other-type-param.expected.fs, test/fsFileTests.fs
```typescript
interface D<TA extends Node = Node, TB extends W<TA> = W<TA>> {}
```
Currently:
```fsharp
type D =
D<Node, W<TA>>
type D<'TA when 'TA :> Node> =
D<'TA, W<'TA>>
type [<AllowNullLiteral>] D<'TA, 'TB when 'TA :> Node and 'TB :> W<'TA>> =
interface end
```
-> First `D` still uses `'TA`. But that gen type param doesn't exist. Instead `TA` is now type...
With this PR:
```fsharp
type D =
D<Node, W<Node>>
```
=> Fix: Default of Generic Type Param that references other defaulted type param keeps source Type param

src/bridge.fs, src/transform.fs, test/fragments/regressions/#467-NonNullable.d.ts, test/fragments/regressions/#467-NonNullable.expected.fs, test/fsFileTests.fs
```typescript
type T1 = NonNullable<string | null | undefined>;
```
Currently:
```fsharp
type T1 = NonNullable<string option>
```
With this PR:
```fsharp
type T1 = string
```
<br/>
Note: Might lead to info getting lost:
```typescript
type T2<T> = W<NonNullable<T>>
```
->
```fsharp
type T2<'T> = W<'T>
```
-> info that `T` must be `NonNullable` gets lost  
Still best we can do in F#. And `null` outside of `option` isn't that common in F#/Fable -> should be ok
<br/>
<br/>
------------
<br/>
<br/>
Note: Besides `NonNullable`, there are [other utility types](https://www.typescriptlang.org/docs/handbook/utility-types.html) in TS. I only handle `NonNullable`. All other utility types stay in F# code.
=> Fix: TS utility Type `NonNullable` still in F# code

src/print.fs, test/fragments/regressions/#468-string-enum-duplicate-fsharp-name.d.ts, test/fragments/regressions/#468-string-enum-duplicate-fsharp-name.expected.fs, test/fsFileTests.fs
```typescript
export type A =
| "utf8"
| "utf-8"
```
Currently:
```fsharp
type [<StringEnum>] [<RequireQualifiedAccess>] A =
| Utf8
| [<CompiledName("utf-8")>] Utf8
```
-> 
> Duplicate definition of union case 'Utf8'
<br/>
with this PR:
```fsharp
type [<StringEnum>] [<RequireQualifiedAccess>] A =
| Utf8
| [<CompiledName("utf-8")>] ``utf-8``
```
=> Fix: Slightly different string enum cases might translate to same F# case name

package-lock.json, package.json
Typescript doesn't follow semver and doesn't guarantee compatibility for minor versions -- only patch versions.
ts2fable pinned TS to minor version (`5.x`), but only works with `5.0` NOT `5.1` -> `npm install` installed new TS version.  
TS is now pinned to `5.0.x`
Fixes https://github.com/fable-compiler/ts2fable/issues/469#issuecomment-1635046034
=> Fix: ts2fable doesn't work because of TS `5.1`
