fable-compiler/ts2fable

ts2fable.js
Following on from #1, Use F# functions instead of delegates.
=> Change System.Func to F# function signatures

ts2fable.js
Following on in #1, add recursive namespace support.
=> Add recursive namespace

src/ts2fable.fs, src/typescript.fs
=> map imports for TS export statements

src/ts2fable.fs, src/typescript.fs
=> import declare variables

src/ts2fable.fs, src/typescript.fs
fix fable-compiler/ts2fable#25
=> erase duplicate types in unions

src/ts2fable.fs, src/typescript.fs
fix fable-compiler/ts2fable#22
=> map `this` references

src/ts2fable.fs, src/typescript.fs
fix fable-compiler/ts2fable#23
=> map CallSignature

src/ts2fable.fs, src/typescript.fs
fix fable-compiler/ts2fable#26
=> import Fable.Import.Browser in case of HTML* type

src/ts2fable.fs
https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#18-overloading-on-string-parameters
fix #36
=> add additional functions for overloaded string params

src/ts2fable.fs, src/typescript.fs
Also disabled printing imports. more work is needed for #21.
=> fix printing submodules

src/ts2fable.fs, src/typescript.fs
fix fable-compiler/ts2fable#43
=> index type can be a float, not just a string

src/ts2fable.fs
fix fable-compiler/ts2fable#42
Identifier.text was null when getText() is not
=> fix React.HTMLProps showing up as undefined

src/ts2fable.fs
=> getText() sometimes has quotes for property name identifiers

package.json, src/read.fs, src/transform.fs, src/ts2fable.fs, src/write.fs, test-compile/test-compile.fsproj, test/test.fs, test/test.fsproj, yarn.lock
=> print out TODO for not yet supported ParamArray

src/Fable.Import.TypeScript.fs, src/read.fs, src/syntax.fs, src/transform.fs, src/ts2fable.fs, src/write.fs
=> import TypeScript comments

appveyor-deploy.ps1, appveyor.yml
This will make it so the `next` tag will be the latest successful build from master.
```
yarn global add ts2fable@next
```
=> continuous deployment to ts2fable@next

src/Fable.Import.TypeScript.fs, src/enum.fs, src/read.fs, src/syntax.fs, src/transform.fs, src/ts2fable.fs, src/write.fs, test-compile/test-compile.fsproj, test/test.fs
Helps with #68, but not a full fix.
=> reduce number of duplicate comments for methods

src/read.fs
Also turn off comments for functions/methods until #68 is fixed.
=> check if param is a string literal

src/Fable.Import.TypeScript.fs, src/read.fs
=> get comments fom the signatures

.babelrc, build.ps1, package.json, yarn.lock
Try to make it work on a Mac with Yarn. #65
=> add shebang using babel

package.json, src/Fable.Import.TypeScript.fs, src/read.fs, src/transform.fs, src/ts2fable.fs, test-compile/test-compile.fsproj, yarn.lock
=> fix reading negative enum cases

src/Fable.Import.TypeScript.fs, src/read.fs, src/syntax.fs, src/transform.fs, src/ts2fable.fs, src/write.fs
I think this is about half of automatic constructors #83. Now we just need to check the base types. Just the parent should be adequate for now.
=> add automatic constructors

package.json, src/Fable.Import.TypeScript.fs, src/read.fs, src/transform.fs, src/ts2fable.fs, yarn.lock
fix fable-compiler/ts2fable#88
=> upgrade to TypeScript 2.6.1

src/naming.fs, test.ps1, test/test.fs
fix fable-compiler/ts2fable#91
=> escape words that begin with underscore

src/Fable.Import.TypeScript.fs, src/naming.fs, src/read.fs, src/syntax.fs, src/transform.fs, src/ts2fable.fs, src/write.fs, test/test.fs
WIP to fix #21
First commit was to get the module names based on
https://github.com/ajafff/tsutils/issues/14#issuecomment-345544684
More info about JS module resolution
http://www.typescriptlang.org/docs/handbook/module-resolution.html
=> map imports

package.json, src/naming.fs, src/read.fs, src/syntax.fs, src/transform.fs, src/ts2fable.fs, src/write.fs, test.ps1, test/test.fs, yarn.lock
This reads the TypeScript import statements and adds F# module aliases or type aliases as needed.
=> read imports

paket.dependencies, paket.lock, src/Node.fs, src/TypeScript.fs, src/paket.references, src/read.fs, src/transform.fs, src/ts2fable.fs, src/ts2fable.fsproj, test-compile/paket.references, test-compile/test-compile.fsproj, test/paket.references
=> using Node module generated by ts2fable

src/Node.fs, src/NodeExt.fs, src/dogfood.ps1, src/ts2fable.fs, src/ts2fable.fsproj, src/watch.ps1, src/write.fs
This pull request makes the generated Node.fs file usable as is from ts2fable without any manual modifications.
=> special case globals for Node

src/NodeExt.fs, src/ts2fable.fs
attempt to print the version when run
=> print the ts2fable version to console

src/ts2fable.fs
https://stackoverflow.com/a/10678373/23059
replaces #111 which did not work
=> get version from package.json

src/Node.fs, src/TypeScript.fs, src/write.fs
fix fable-compiler/ts2fable#114
=> paramarray as an array

package.json, paket.lock, src/Yargs.fs, src/build.ps1, src/dogfood.ps1, src/start.ps1, src/ts2fable.fs, src/ts2fable.fsproj, test-compile/test-compile.fsproj, yarn.lock
fix fable-compiler/ts2fable#87
=> use yargs to parse command line options

src/Node.fs, src/TypeScript.fs, src/Yargs.fs, src/transform.fs
Quick follow up to #123 and https://github.com/fable-compiler/Fable/issues/1254 after I realized that I just needed to delete my NodeExt.fs which was causing the conflicts.
=> alias union helpers in the same package

src/print.fs, src/read.fs, src/syntax.fs, src/transform.fs, src/write.fs
fix fable-compiler/ts2fable#89
=> import @param documentation comments

package.json, src/ts2fable.fs, test-compile/test-compile.fsproj, yarn.lock
=> specify vscode version with environment variable

build-update-package.js, build.ps1, package.json
=> remove scripts section of package.json during a build

build-update-package.js
=> remove engines section from packages.json

appveyor.yml, package.json, paket.lock, src/Node.fs, src/ts2fable.fs, update.ps1, yarn.lock
=> fix #122 some Node constants not mapped

src/Node.fs, src/ts2fable.fs, update.ps1, yarn.lock
=> Node _debugger gone after @types update

src/naming.fs
=> Support scoped packages

src/transform.fs
=> Duplicated Variable Exports

.vscode/launch.json, src/naming.fs, src/syntax.fs, src/transform.fs, test/fsFileTests.fs, test/functionTests.fs
=> fix getJsModuleName function

tools/deploy.fsx
refix https://github.com/fable-compiler/ts2fable/pull/173
=> pushToExports

src/syntax.fs, src/transform.fs, src/write.fs, test/fsFileTests.fs
=> Fix Option.map to full namespace

src/read.fs, src/syntax.fs, src/transform.fs, src/write.fs, test/fragments/react/f3.d.ts, test/fragments/react/f3.fs, test/fsFileTests.fs, tools/deploy.fsx
=> Typescript generic parameter defaults

src/keywords.fs, src/syntax.fs, src/transform.fs, src/write.fs, test/fragments/react/f4.d.ts, test/fragments/react/f4.fs, test/fsFileTests.fs, tools/deploy.fsx
=> Es keywords

src/keywords.fs, src/transform.fs, src/write.fs, test/fragments/react/f5.d.ts, test/fragments/react/f5.fs, test/fsFileTests.fs
=> Extract types in global modules

package.json, src/ts2fable.fs, yarn.lock
In Fable repl, and another project I am working on for Fable eco-system I need to use Monaco.
I think it's a good thing to add it's bindings to the project. Please tell, if I missed something :)
=> Add monaco-editor to auto generated files

.paket/Paket.Restore.targets, .vscode/launch.json, src/transform.fs, test/fragments/react/f7.d.ts, test/fragments/react/f7.fs, test/fsFileTests.fs
=> Extract type literal from type alias

package.json
fix #196, broken by #163, I think
=> make ts2fable@next yarn add work again

build.fsx, package.json, tools/add-shebang.js, yarn.lock
=> add shebang back to ts2fable.js

src/read.fs, src/syntax.fs, src/transform.fs, test-compile/test-compile.fsproj, test/fragments/react/f8.d.ts, test/fragments/react/f8.fs, test/fsFileTests.fs
=> [React] Map mapped types(2)

package.json, src/keywords.fs, src/transform.fs, test/fragments/react/f4.d.ts, test/fragments/react/f4.fs
=> Update react & reactxp version

build.fsx, test-compile/test-compile.fsproj
As reactxp depends on `synctasks and subscribableevent` ,so i added it
=> Add synctasks & subscribableevent to auto generated files

src/Yargs.fs, src/transform.fs, src/write.fs, test/fragments/yargs/duplicateOption.d.ts, test/fragments/yargs/duplicateOption.fs, test/fsFileTests.fs
=> Remove duplicate options

.vscode/launch.json, .vscode/tasks.json, build.fsx, src/ts2fable.fs, src/write.fs, test/fsFileTests.fs, tools/webpack.config.cli.js
With this, you can specify a filter for files to export:
`--exports uifabric office-ui-fabric-react`
There are other issues with the office export, but this pull request is for the command line options.
```
C:\Users\camer\fs\ts2fable [master ≡ +0 ~2 -0 !]> node ./dist/ts2fable.js node_modules/office-ui-fabric-react/lib/index.d.ts test-compile/OfficeReact.fs -e uifabric office-ui-fabric-react
ts2fable 0.0.0
export C:/Users/camer/fs/ts2fable/node_modules/@uifabric/utilities/lib/Async.d.ts
export C:/Users/camer/fs/ts2fable/node_modules/@uifabric/utilities/lib/AutoScroll.d.ts
export C:/Users/camer/fs/ts2fable/node_modules/@uifabric/utilities/lib/EventGroup.d.ts
export C:/Users/camer/fs/ts2fable/node_modules/@uifabric/utilities/lib/IDisposable.d.ts
export …
```
=> add exports option

.vscode/tasks.json, src/bridge.fs, src/node/fileSystem.fs, src/node/write.fs, src/ts2fable.fsproj, src/write.fs
=> Imporve performance of fsfile tests

.vscode/tasks.json, build2.fsx, common.fsx
=> Idealy workflow

common.fsx, src/bridge.fs, src/naming.fs, src/node/fileSystem.fs, src/node/write.fs, src/syntax.fs, src/transform.fs, test/fragments/reactxp/ReactXP.d.ts, test/fragments/reactxp/duplicatedVariableExports.fs, test/fragments/reactxp/web/ReactXP.d.ts, test/fragments/reactxp/wrapperModuleForExtraFile.fs, test/fsFileTests.fs
=> wrap module to extra file

yarn.lock
fixes https://github.com/fable-compiler/ts2fable/issues/257
=> downgrade eslint-scope to 3.7.1 from 3.7.2

package.json, yarn.lock
I updated in `package.json` and then did a `yarn install`
=> update vscode to 1.1.21

common.fsx
Waiting for the CI to complete to see if we actually **do not** deploy the web app from PR.
=> Fix + Re-activate WebApp.Publish for auto deployment

common.fsx
Reverts fable-compiler/ts2fable#264
=> Revert "Fix + Re-activate WebApp.Publish for auto deployment"

README.md
=> Also restore dotnet-fake

src/transform.fs
Typescript: 
```ts
static MinMax(meshes: AbstractMesh[]): {
min: Vector3;
max: Vector3;
};
```
Before/After:
```f#
type [<AllowNullLiteral>] MeshStaticMinMaxReturn =
abstract min: Vector3 with get, set
abstract max: Vector3 with get, set
```
closes https://github.com/fable-compiler/ts2fable/issues/274
=> also transform TypeLiterals in return types of methods

src/transform.fs
fixes https://github.com/fable-compiler/ts2fable/issues/280
=> merge duplicated inner modules after merging the outer modules

src/read.fs, src/syntax.fs, src/transform.fs, test/fragments/regressions/#292-static-props.d.ts, test/fragments/regressions/#292-static-props.expected.fs, test/fsFileTests.fs
fixes https://github.com/fable-compiler/ts2fable/issues/292
=> handle static properties

common.fsx
@humhei Hopefully that fixes it.
=> cli-publish fix

common.fsx
This was probably broken before I touched it ;)
=> WebApp.Publish fix

package.json
Seems the build script cause the issue
=> Fixes #334

src/transform.fs, test/fragments/react/f3.fs, test/fragments/regressions/#352-generic-type-parameter-default.d.ts, test/fragments/regressions/#352-generic-type-parameter-default.expected.fs, test/fragments/regressions/#353-generic-type-parameter-default-type.d.ts, test/fragments/regressions/#353-generic-type-parameter-default-type.expected.fs, test/fsFileTests.fs
=> Fix #352 & #353: generic type parameter defaults

src/naming.fs, test/fragments/reactxp/duplicatedVariableExports.fs, test/functionTests.fs
=> Fix: Wrong module name

src/print.fs, test/fragments/custom/generic-type-constraints/.gitignore, test/fragments/react/f2.fs, test/fragments/regressions/#362-paramarray.d.ts, test/fragments/regressions/#362-paramarray.expected.fs, test/fsFileTests.fs
=> Fix #362: Use Array with ParamArray

src/bridge.fs, src/print.fs, src/read.fs, src/syntax.fs, src/transform.fs, test/fragments/regressions/#348-getter-setter.d.ts, test/fragments/regressions/#348-getter-setter.expected.fs, test/fsFileTests.fs
Fix #348: Add support for getter & setter
=> Fix #348: Add support for getter & setter

src/transformComments.fs, test/fragments/regressions/#420-xml-comment-generic-type-param-in-param.d.ts, test/fragments/regressions/#420-xml-comment-generic-type-param-in-param.expected.fs, test/fsFileTests.fs
=> Fix #420: Convert `@param` with generic type param into `<typeparam ...`

test/fsFileTests.fs
trailing `.timeout(...)` on a test suite (`describe`) doesn't work -- suffix `timeout`-method only works on individual tests.
This PR fixes this by using `this.timeout(...)` at start of `describe` (again)
=> Fix: Tests ignore custom timeout

.config/dotnet-tools.json
=> dotnet tools update
